// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:lilinet_app/features/comments/data/models/local_comment_model.dart';
import 'package:lilinet_app/features/explore/data/models/category_model.dart';
import 'package:lilinet_app/features/explore/data/models/genre_model.dart';
import 'package:lilinet_app/features/history/data/models/watch_progress_model.dart';
import 'package:lilinet_app/features/movies/data/models/episode_model.dart';
import 'package:lilinet_app/features/movies/data/models/movie_model.dart';
import 'package:lilinet_app/features/movies/data/models/season_model.dart';
import 'package:lilinet_app/features/movies/data/models/streaming_link_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CategoryModelAdapter());
    registerAdapter(EpisodeModelAdapter());
    registerAdapter(GenreModelAdapter());
    registerAdapter(LocalCommentModelAdapter());
    registerAdapter(MovieListResponseAdapter());
    registerAdapter(MovieModelAdapter());
    registerAdapter(SeasonModelAdapter());
    registerAdapter(StreamingLinkModelAdapter());
    registerAdapter(StreamingResponseModelAdapter());
    registerAdapter(SubtitleModelAdapter());
    registerAdapter(WatchProgressModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CategoryModelAdapter());
    registerAdapter(EpisodeModelAdapter());
    registerAdapter(GenreModelAdapter());
    registerAdapter(LocalCommentModelAdapter());
    registerAdapter(MovieListResponseAdapter());
    registerAdapter(MovieModelAdapter());
    registerAdapter(SeasonModelAdapter());
    registerAdapter(StreamingLinkModelAdapter());
    registerAdapter(StreamingResponseModelAdapter());
    registerAdapter(SubtitleModelAdapter());
    registerAdapter(WatchProgressModelAdapter());
  }
}
